apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
data:
  # echo -n "root" | base64
  POSTGRES_PASSWORD: cm9vdA==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  # storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.4
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - gosu postgres pg_ctl -D /var/lib/postgresql/data -m fast -w stop
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: data
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 1Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres
