apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - args:
        - --databases 1
        - --maxmemory 200mb
        - --maxmemory-policy allkeys-lru
        - --appendonly no
        - --save ""
        image: redis:4.0.11
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 210Mi
  updateStrategy:
    type: OnDelete
