apiVersion: v1
kind: Service
metadata:
  name: zipkin-collector
  labels:
    app: zipkin-collector
spec:
  selector:
    app: zipkin-collector
  ports:
  - name: http
    port: 9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-collector
  labels:
    app: zipkin-collector
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: zipkin-collector
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      name: zipkin-collector
      labels:
        app: zipkin-collector
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zipkin-collector
            topologyKey: kubernetes.io/hostname
      containers:
      - name: zipkin-collector
        image: gcr.io/stackdriver-trace-docker/zipkin-collector:v0.6.0
        ports:
        - containerPort: 9411
        resources:
          requests:
            cpu: 20m
            memory: 250Mi
          limits:
            memory: 400Mi
