apiVersion: v1
kind: Service
metadata:
  name: zipkin-gcp
  labels:
    app: zipkin-gcp
spec:
  selector:
    app: zipkin-gcp
  ports:
  - name: http
    port: 9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-gcp
  labels:
    app: zipkin-gcp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: zipkin-gcp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      name: zipkin-gcp
      labels:
        app: zipkin-gcp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
      containers:
      - name: zipkin-gcp
        image: quay.io/openzipkin/zipkin-gcp:0.8.2
        ports:
        - containerPort: 9411
        resources:
          requests:
            cpu: 5m
            memory: 250Mi
          limits:
            memory: 400Mi
