apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres10
  labels:
    app: postgres10
spec:
  storageClassName: ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
