apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres10
  labels:
    app: postgres10
spec:
  serviceName: postgres10
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres10
    spec:
      containers:
      - name: postgres
        image: postgres:10.0
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres10
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres10
