apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:tag
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe: &probe
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 5
        livenessProbe: *probe
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: secret
          mountPath: /secret
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: myapp
      - name: secret
        secret:
          secretName: myapp
          defaultMode: 0600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
