kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-exporter
  namespace: prometheus
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      name: redis-exporter
      namespace: prometheus
      labels:
        app: redis-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9121'
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter
        imagePullPolicy: Always
        args:
        - -redis.addr=redis://redis:6379
        ports:
        - containerPort: 9121
        resources:
          requests:
            cpu: 5m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi
