apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  storageClassName: ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
