apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  storageClassName: ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
